<?php
return array(
	'user' => 'NAME, USERNAME, EMAIL, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, COMPANY_WEBSITE, CURRENT_DATE_TIME, COMPANY_ADDRESS, CURRENT_DATE, DATE_OF_BIRTH, DATE_OF_ANNIVERSARY, DEPARTMENT, DESIGNATION, LOCATION, COMPANY_LOGO',
	'payroll' => 'NAME, USERNAME, EMAIL, DEPARTMENT, DESIGNATION, LOCATION, DATE_OF_PAYROLL, PAYROLL_FROM_DATE, PAYROLL_TO_DATE, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, COMPANY_WEBSITE, CURRENT_DATE_TIME, COMPANY_ADDRESS, CURRENT_DATE, COMPANY_LOGO'
	);